[package]
name = "cosmoz"
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "Pure Rust zstd compressor and decompressor, no_std core, native and wasm"
repository = "https://github.com/josoriom/cosmoz"
readme = "README.md"
keywords = ["zstd", "compression", "wasm"]
categories = ["compression", "no-std", "wasm"]
authors = [
    "Javier Osorio M <javier.osorio.mosquera@gmail.com>",
    "Jorge Osorio M <joheosmo@gmail.com>"
]

[lib]
crate-type = ["rlib"]

[features]
default = ["checksum"]
checksum = []
compression = []
std = []
parallel = ["std"]
wasm-exports = []

[dependencies]

[dev-dependencies]
cosmoz = { path = ".", features = ["std", "compression"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
