[package]
name = "osmo"
version = "0.1.0"
edition = "2024"
authors = [
    "Javier Osorio M <javier.osorio.mosquera@gmail.com>",
    "Jorge Osorio M <joheosmo@gmail.com>"
]

[lib]
crate-type = ["rlib"]

[features]
default = []
alloc = []
std = ["alloc"]
parallel = ["std"]
wasm-exports = []

[dependencies]

[dev-dependencies]
osmo = { path = ".", features = ["std"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
