#[cfg(feature = "compression")]
pub(crate) mod binary_tree_matcher;
pub(crate) mod fast;
#[cfg(feature = "compression")]
pub(crate) mod lazy2;
#[cfg(feature = "compression")]
pub(crate) mod symbol_prices;
#[cfg(feature = "compression")]
pub(crate) mod ultra2;
